"""Curated offline-style phrasebook seed data, ported from the Bhasha design mockup."""

LANGUAGES = [
    {"code": "en", "name": "English", "native": "English", "bcp47": "en-US", "group": "English & Indian languages", "is_phrasebook": True},
    {"code": "hi", "name": "Hindi", "native": "हिन्दी", "bcp47": "hi-IN", "group": "English & Indian languages", "is_phrasebook": True},
    {"code": "te", "name": "Telugu", "native": "తెలుగు", "bcp47": "te-IN", "group": "English & Indian languages", "is_phrasebook": True},
    {"code": "ta", "name": "Tamil", "native": "தமிழ்", "bcp47": "ta-IN", "group": "English & Indian languages", "is_phrasebook": True},
    {"code": "kn", "name": "Kannada", "native": "ಕನ್ನಡ", "bcp47": "kn-IN", "group": "English & Indian languages", "is_phrasebook": True},
    {"code": "ml", "name": "Malayalam", "native": "മലയാളം", "bcp47": "ml-IN", "group": "English & Indian languages", "is_phrasebook": True},
    {"code": "bn", "name": "Bengali", "native": "বাংলা", "bcp47": "bn-IN", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "mr", "name": "Marathi", "native": "मराठी", "bcp47": "mr-IN", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "gu", "name": "Gujarati", "native": "ગુજરાતી", "bcp47": "gu-IN", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "pa", "name": "Punjabi", "native": "ਪੰਜਾਬੀ", "bcp47": "pa-IN", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "ur", "name": "Urdu", "native": "اردو", "bcp47": "ur-IN", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "or", "name": "Odia", "native": "ଓଡ଼ିଆ", "bcp47": "or-IN", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "as", "name": "Assamese", "native": "অসমীয়া", "bcp47": "as-IN", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "ne", "name": "Nepali", "native": "नेपाली", "bcp47": "ne-NP", "group": "English & Indian languages", "is_phrasebook": False},
    {"code": "si", "name": "Sinhala", "native": "සිංහල", "bcp47": "si-LK", "group": "English & Indian languages", "is_phrasebook": False},

    {"code": "zh", "name": "Chinese (Simplified)", "native": "中文", "bcp47": "zh-CN", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "zhTW", "name": "Chinese (Traditional)", "native": "中文(繁體)", "bcp47": "zh-TW", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "ja", "name": "Japanese", "native": "日本語", "bcp47": "ja-JP", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "ko", "name": "Korean", "native": "한국어", "bcp47": "ko-KR", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "th", "name": "Thai", "native": "ไทย", "bcp47": "th-TH", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "vi", "name": "Vietnamese", "native": "Tiếng Việt", "bcp47": "vi-VN", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "id", "name": "Indonesian", "native": "Bahasa Indonesia", "bcp47": "id-ID", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "ms", "name": "Malay", "native": "Bahasa Melayu", "bcp47": "ms-MY", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "tl", "name": "Filipino", "native": "Filipino", "bcp47": "fil-PH", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "my", "name": "Burmese", "native": "မြန်မာ", "bcp47": "my-MM", "group": "East & Southeast Asia", "is_phrasebook": False},
    {"code": "mn", "name": "Mongolian", "native": "Монгол", "bcp47": "mn-MN", "group": "East & Southeast Asia", "is_phrasebook": False},

    {"code": "es", "name": "Spanish", "native": "Español", "bcp47": "es-ES", "group": "Europe", "is_phrasebook": True},
    {"code": "fr", "name": "French", "native": "Français", "bcp47": "fr-FR", "group": "Europe", "is_phrasebook": True},
    {"code": "de", "name": "German", "native": "Deutsch", "bcp47": "de-DE", "group": "Europe", "is_phrasebook": False},
    {"code": "it", "name": "Italian", "native": "Italiano", "bcp47": "it-IT", "group": "Europe", "is_phrasebook": False},
    {"code": "pt", "name": "Portuguese", "native": "Português", "bcp47": "pt-PT", "group": "Europe", "is_phrasebook": False},
    {"code": "nl", "name": "Dutch", "native": "Nederlands", "bcp47": "nl-NL", "group": "Europe", "is_phrasebook": False},
    {"code": "ru", "name": "Russian", "native": "Русский", "bcp47": "ru-RU", "group": "Europe", "is_phrasebook": False},
    {"code": "uk", "name": "Ukrainian", "native": "Українська", "bcp47": "uk-UA", "group": "Europe", "is_phrasebook": False},
    {"code": "pl", "name": "Polish", "native": "Polski", "bcp47": "pl-PL", "group": "Europe", "is_phrasebook": False},
    {"code": "sv", "name": "Swedish", "native": "Svenska", "bcp47": "sv-SE", "group": "Europe", "is_phrasebook": False},
    {"code": "no", "name": "Norwegian", "native": "Norsk", "bcp47": "nb-NO", "group": "Europe", "is_phrasebook": False},
    {"code": "da", "name": "Danish", "native": "Dansk", "bcp47": "da-DK", "group": "Europe", "is_phrasebook": False},
    {"code": "fi", "name": "Finnish", "native": "Suomi", "bcp47": "fi-FI", "group": "Europe", "is_phrasebook": False},
    {"code": "el", "name": "Greek", "native": "Ελληνικά", "bcp47": "el-GR", "group": "Europe", "is_phrasebook": False},
    {"code": "cs", "name": "Czech", "native": "Čeština", "bcp47": "cs-CZ", "group": "Europe", "is_phrasebook": False},
    {"code": "hu", "name": "Hungarian", "native": "Magyar", "bcp47": "hu-HU", "group": "Europe", "is_phrasebook": False},
    {"code": "ro", "name": "Romanian", "native": "Română", "bcp47": "ro-RO", "group": "Europe", "is_phrasebook": False},

    {"code": "ar", "name": "Arabic", "native": "العربية", "bcp47": "ar-SA", "group": "Middle East & Africa", "is_phrasebook": False},
    {"code": "he", "name": "Hebrew", "native": "עברית", "bcp47": "he-IL", "group": "Middle East & Africa", "is_phrasebook": False},
    {"code": "fa", "name": "Persian", "native": "فارسی", "bcp47": "fa-IR", "group": "Middle East & Africa", "is_phrasebook": False},
    {"code": "tr", "name": "Turkish", "native": "Türkçe", "bcp47": "tr-TR", "group": "Middle East & Africa", "is_phrasebook": False},
    {"code": "sw", "name": "Swahili", "native": "Kiswahili", "bcp47": "sw-KE", "group": "Middle East & Africa", "is_phrasebook": False},
    {"code": "zu", "name": "Zulu", "native": "isiZulu", "bcp47": "zu-ZA", "group": "Middle East & Africa", "is_phrasebook": False},
    {"code": "am", "name": "Amharic", "native": "አማርኛ", "bcp47": "am-ET", "group": "Middle East & Africa", "is_phrasebook": False},
]

PHRASES = [
    {"slug": "hello", "translations": {"en": "Hello", "te": "నమస్కారం", "hi": "नमस्ते", "ta": "வணக்கம்", "kn": "ನಮಸ್ಕಾರ", "ml": "നമസ്കാരം", "es": "Hola", "fr": "Bonjour"}, "translit": {"te": ["namaskaram"], "hi": ["namaste"]}},
    {"slug": "how_are_you", "translations": {"en": "How are you?", "te": "ఎలా వున్నారు?", "hi": "आप कैसे हैं?", "ta": "நீங்கள் எப்படி இருக்கிறீர்கள்?", "kn": "ನೀವು ಹೇಗಿದ್ದೀರಿ?", "ml": "സുഖമാണോ?", "es": "¿Cómo estás?", "fr": "Comment ça va ?"}, "translit": {"te": ["ela vunnaru", "ela unnaru", "yela vunnaru", "elavunnaru"], "hi": ["aap kaise hain", "kaise ho"]}},
    {"slug": "good_morning", "translations": {"en": "Good morning", "te": "శుభోదయం", "hi": "सुप्रभात", "ta": "காலை வணக்கம்", "kn": "ಶುಭೋದಯ", "ml": "സുപ്രഭാതം", "es": "Buenos días", "fr": "Bonjour"}, "translit": {"te": ["shubhodayam"], "hi": ["suprabhat"]}},
    {"slug": "good_night", "translations": {"en": "Good night", "te": "శుభరాత్రి", "hi": "शुभ रात्रि", "ta": "இனிய இரவு", "kn": "ಶುಭ ರಾತ್ರಿ", "ml": "ശുഭരാത്രി", "es": "Buenas noches", "fr": "Bonne nuit"}, "translit": {"te": ["shubharatri"], "hi": ["shubh ratri"]}},
    {"slug": "thank_you", "translations": {"en": "Thank you", "te": "ధన్యవాదాలు", "hi": "धन्यवाद", "ta": "நன்றி", "kn": "ಧನ್ಯವಾದಗಳು", "ml": "നന്ദി", "es": "Gracias", "fr": "Merci"}, "translit": {"te": ["dhanyavadalu"], "hi": ["dhanyavaad", "shukriya"]}},
    {"slug": "please", "translations": {"en": "Please", "te": "దయచేసి", "hi": "कृपया", "ta": "தயவுசெய்து", "kn": "ದಯವಿಟ್ಟು", "ml": "ദയവായി", "es": "Por favor", "fr": "S'il vous plaît"}, "translit": {"te": ["dayachesi"], "hi": ["kripya"]}},
    {"slug": "yes", "translations": {"en": "Yes", "te": "అవును", "hi": "हाँ", "ta": "ஆம்", "kn": "ಹೌದು", "ml": "അതെ", "es": "Sí", "fr": "Oui"}, "translit": {"te": ["avunu"], "hi": ["haan"]}},
    {"slug": "no", "translations": {"en": "No", "te": "కాదు", "hi": "नहीं", "ta": "இல்லை", "kn": "ಇಲ್ಲ", "ml": "ഇല്ല", "es": "No", "fr": "Non"}, "translit": {"te": ["kaadu", "kadu"], "hi": ["nahi", "nahin"]}},
    {"slug": "sorry", "translations": {"en": "Sorry", "te": "క్షమించండి", "hi": "माफ़ कीजिए", "ta": "மன்னிக்கவும்", "kn": "ಕ್ಷಮಿಸಿ", "ml": "ക്ഷമിക്കണം", "es": "Lo siento", "fr": "Pardon"}, "translit": {"te": ["kshaminchandi"], "hi": ["maaf kijiye"]}},
    {"slug": "whats_your_name", "translations": {"en": "What is your name?", "te": "మీ పేరు ఏమిటి?", "hi": "आपका नाम क्या है?", "ta": "உங்கள் பெயர் என்ன?", "kn": "ನಿಮ್ಮ ಹೆಸರೇನು?", "ml": "നിന്റെ പേരെന്താണ്?", "es": "¿Cómo te llamas?", "fr": "Comment vous appelez-vous ?"}, "translit": {"te": ["mee peru emiti"], "hi": ["aapka naam kya hai"]}},
    {"slug": "my_name_is", "translations": {"en": "My name is", "te": "నా పేరు", "hi": "मेरा नाम है", "ta": "என் பெயர்", "kn": "ನನ್ನ ಹೆಸರು", "ml": "എന്റെ പേര്", "es": "Me llamo", "fr": "Je m'appelle"}, "translit": {"te": ["naa peru"], "hi": ["mera naam hai"]}},
    {"slug": "where_are_you_from", "translations": {"en": "Where are you from?", "te": "మీరు ఎక్కడ నుండి వచ్చారు?", "hi": "आप कहाँ से हैं?", "ta": "நீங்கள் எங்கிருந்து வருகிறீர்கள்?", "kn": "ನೀವು ಎಲ್ಲಿಂದ ಬಂದಿದ್ದೀರಿ?", "ml": "നിങ്ങൾ എവിടെ നിന്നാണ്?", "es": "¿De dónde eres?", "fr": "D'où venez-vous ?"}, "translit": {"te": ["meeru ekkada nundi vacharu"], "hi": ["aap kahan se hain"]}},
    {"slug": "i_am_fine", "translations": {"en": "I am fine", "te": "నేను బాగున్నాను", "hi": "मैं ठीक हूँ", "ta": "நான் நலமாக இருக்கிறேன்", "kn": "ನಾನು ಚೆನ್ನಾಗಿದ್ದೇನೆ", "ml": "എനിക്ക് സുഖമാണ്", "es": "Estoy bien", "fr": "Je vais bien"}, "translit": {"te": ["nenu baagunnanu", "nenu bagunnanu"], "hi": ["main theek hoon", "main thik hu"]}},
    {"slug": "see_you_later", "translations": {"en": "See you later", "te": "తర్వాత కలుద్దాం", "hi": "बाद में मिलते हैं", "ta": "பின்னர் சந்திப்போம்", "kn": "ನಂತರ ಸಿಗೋಣ", "ml": "പിന്നീട് കാണാം", "es": "Nos vemos luego", "fr": "À plus tard"}, "translit": {"te": ["tarvata kaluddam"], "hi": ["baad mein milte hain"]}},
    {"slug": "good_bye", "translations": {"en": "Goodbye", "te": "వీడ్కోలు", "hi": "अलविदा", "ta": "பிரியாவிடை", "kn": "ವಿದಾಯ", "ml": "വിട", "es": "Adiós", "fr": "Au revoir"}, "translit": {"te": ["veedkolu"], "hi": ["alvida"]}},
    {"slug": "how_much", "translations": {"en": "How much is this?", "te": "ఇది ఎంత?", "hi": "यह कितने का है?", "ta": "இது எவ்வளவு?", "kn": "ಇದು ಎಷ್ಟು?", "ml": "ഇതിന് എത്ര വില?", "es": "¿Cuánto cuesta esto?", "fr": "Combien ça coûte ?"}, "translit": {"te": ["idi entha"], "hi": ["yah kitne ka hai"]}},
    {"slug": "where_is_bathroom", "translations": {"en": "Where is the bathroom?", "te": "బాత్రూమ్ ఎక్కడ ఉంది?", "hi": "शौचालय कहाँ है?", "ta": "கழிப்பறை எங்கே?", "kn": "ಶೌಚಾಲಯ ಎಲ್ಲಿದೆ?", "ml": "ശുചിമുറി എവിടെയാണ്?", "es": "¿Dónde está el baño?", "fr": "Où sont les toilettes ?"}, "translit": {"te": ["bathroom ekkada undi"], "hi": ["shauchalay kahan hai"]}},
    {"slug": "i_dont_understand", "translations": {"en": "I don't understand", "te": "నాకు అర్థం కాలేదు", "hi": "मुझे समझ नहीं आया", "ta": "எனக்கு புரியவில்லை", "kn": "ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ", "ml": "എനിക്ക് മനസ്സിലായില്ല", "es": "No entiendo", "fr": "Je ne comprends pas"}, "translit": {"te": ["naaku artham kaledu"], "hi": ["mujhe samajh nahin aaya"]}},
    {"slug": "can_you_help_me", "translations": {"en": "Can you help me?", "te": "మీరు నాకు సహాయం చేయగలరా?", "hi": "क्या आप मेरी मदद कर सकते हैं?", "ta": "நீங்கள் எனக்கு உதவ முடியுமா?", "kn": "ನೀವು ನನಗೆ ಸಹಾಯ ಮಾಡಬಲ್ಲಿರಾ?", "ml": "നിങ്ങൾക്ക് എന്നെ സഹായിക്കാമോ?", "es": "¿Puedes ayudarme?", "fr": "Pouvez-vous m'aider ?"}, "translit": {"te": ["meeru naaku sahayam cheyagalara"], "hi": ["kya aap meri madad kar sakte hain"]}},
    {"slug": "i_love_you", "translations": {"en": "I love you", "te": "నేను నిన్ను ప్రేమిస్తున్నాను", "hi": "मैं तुमसे प्यार करता हूँ", "ta": "நான் உன்னை காதலிக்கிறேன்", "kn": "ನಾನು ನಿನ್ನನ್ನು ಪ್ರೀತಿಸುತ್ತೇನೆ", "ml": "ഞാൻ നിന്നെ സ്നേഹിക്കുന്നു", "es": "Te quiero", "fr": "Je t'aime"}, "translit": {"te": ["nenu ninnu premisthunnanu"], "hi": ["main tumse pyaar karta hoon"]}},
    {"slug": "water", "translations": {"en": "Water", "te": "నీళ్ళు", "hi": "पानी", "ta": "தண்ணீர்", "kn": "ನೀರು", "ml": "വെള്ളം", "es": "Agua", "fr": "Eau"}, "translit": {"te": ["neellu"], "hi": ["paani"]}},
    {"slug": "food", "translations": {"en": "Food", "te": "ఆహారం", "hi": "खाना", "ta": "உணவு", "kn": "ಆಹಾರ", "ml": "ഭക്ഷണം", "es": "Comida", "fr": "Nourriture"}, "translit": {"te": ["aaharam"], "hi": ["khaana"]}},
    {"slug": "what_time", "translations": {"en": "What time is it?", "te": "సమయం ఎంత అయింది?", "hi": "अभी क्या समय है?", "ta": "இப்போது என்ன நேரம்?", "kn": "ಈಗ ಎಷ್ಟು ಗಂಟೆ?", "ml": "ഇപ്പോൾ എത്ര സമയമായി?", "es": "¿Qué hora es?", "fr": "Quelle heure est-il ?"}, "translit": {"te": ["samayam entha ayindi"], "hi": ["abhi kya samay hai"]}},
    {"slug": "nice_to_meet_you", "translations": {"en": "Nice to meet you", "te": "మిమ్మల్ని కలవడం సంతోషంగా ఉంది", "hi": "आपसे मिलकर खुशी हुई", "ta": "உங்களை சந்தித்ததில் மகிழ்ச்சி", "kn": "ನಿಮ್ಮನ್ನು ಭೇಟಿಯಾಗಿ ಸಂತೋಷವಾಯಿತು", "ml": "നിങ്ങളെ കണ്ടതിൽ സന്തോഷം", "es": "Mucho gusto", "fr": "Enchanté(e)"}, "translit": {"te": ["mimmalni kalavadam santoshanga undi"], "hi": ["aapse milkar khushi hui"]}},
    {"slug": "good_afternoon", "translations": {"en": "Good afternoon", "te": "శుభ మధ్యాహ్నం", "hi": "शुभ दोपहर", "ta": "மதிய வணக்கம்", "kn": "ಶುಭ ಮಧ್ಯಾಹ್ನ", "ml": "ശുഭ മധ്യാഹ്നം", "es": "Buenas tardes", "fr": "Bon après-midi"}, "translit": {"te": ["shubha madhyahnam"], "hi": ["shubh dopahar"]}},
    {"slug": "welcome", "translations": {"en": "Welcome", "te": "స్వాగతం", "hi": "स्वागत है", "ta": "வருக", "kn": "ಸ್ವಾಗತ", "ml": "സ്വാഗതം", "es": "Bienvenido", "fr": "Bienvenue"}, "translit": {"te": ["swagatam"], "hi": ["swagat hai"]}},
    {"slug": "congratulations", "translations": {"en": "Congratulations", "te": "అభినందనలు", "hi": "बधाई हो", "ta": "வாழ்த்துக்கள்", "kn": "ಅಭಿನಂದನೆಗಳು", "ml": "അഭിനന്ദനങ്ങൾ", "es": "Felicidades", "fr": "Félicitations"}, "translit": {"te": ["abhinandanalu"], "hi": ["badhai ho"]}},
    {"slug": "happy_birthday", "translations": {"en": "Happy birthday", "te": "పుట్టినరోజు శుభాకాంక్షలు", "hi": "जन्मदिन मुबारक हो", "ta": "பிறந்தநாள் வாழ்த்துக்கள்", "kn": "ಹುಟ್ಟುಹಬ್ಬದ ಶುಭಾಶಯಗಳು", "ml": "ജന്മദിനാശംസകൾ", "es": "Feliz cumpleaños", "fr": "Joyeux anniversaire"}, "translit": {"te": ["puttinaroju shubhakankshalu"], "hi": ["janmadin mubarak ho"]}},
    {"slug": "i_am_hungry", "translations": {"en": "I am hungry", "te": "నాకు ఆకలిగా ఉంది", "hi": "मुझे भूख लगी है", "ta": "எனக்கு பசிக்குது", "kn": "ನನಗೆ ಹಸಿವಾಗಿದೆ", "ml": "എനിക്ക് വിശക്കുന്നു", "es": "Tengo hambre", "fr": "J'ai faim"}, "translit": {"te": ["naaku aakaliga undi"], "hi": ["mujhe bhookh lagi hai"]}},
    {"slug": "i_am_thirsty", "translations": {"en": "I am thirsty", "te": "నాకు దాహంగా ఉంది", "hi": "मुझे प्यास लगी है", "ta": "எனக்கு தாகமாக இருக்கிறது", "kn": "ನನಗೆ ಬಾಯಾರಿಕೆಯಾಗಿದೆ", "ml": "എനിക്ക് ദാഹിക്കുന്നു", "es": "Tengo sed", "fr": "J'ai soif"}, "translit": {"te": ["naaku dahamga undi"], "hi": ["mujhe pyaas lagi hai"]}},
    {"slug": "where_is_hotel", "translations": {"en": "Where is the hotel?", "te": "హోటల్ ఎక్కడ ఉంది?", "hi": "होटल कहाँ है?", "ta": "ஹோட்டல் எங்கே?", "kn": "ಹೋಟೆಲ್ ಎಲ್ಲಿದೆ?", "ml": "ഹോട്ടൽ എവിടെയാണ്?", "es": "¿Dónde está el hotel?", "fr": "Où est l'hôtel ?"}, "translit": {"te": ["hotel ekkada undi"], "hi": ["hotel kahan hai"]}},
    {"slug": "do_you_speak_english", "translations": {"en": "Do you speak English?", "te": "మీకు ఇంగ్లీష్ వచ్చా?", "hi": "क्या आप अंग्रेज़ी बोलते हैं?", "ta": "நீங்கள் ஆங்கிலம் பேசுவீர்களா?", "kn": "ನಿಮಗೆ ಇಂಗ್ಲಿಷ್ ಬರುತ್ತದೆಯೇ?", "ml": "നിങ്ങൾക്ക് ഇംഗ്ലീഷ് അറിയാമോ?", "es": "¿Hablas inglés?", "fr": "Parlez-vous anglais ?"}, "translit": {"te": ["meeku english vachcha"], "hi": ["kya aap angrezi bolte hain"]}},
    {"slug": "what_is_this", "translations": {"en": "What is this?", "te": "ఇది ఏమిటి?", "hi": "यह क्या है?", "ta": "இது என்ன?", "kn": "ಇದೇನು?", "ml": "ഇത് എന്താണ്?", "es": "¿Qué es esto?", "fr": "Qu'est-ce que c'est ?"}, "translit": {"te": ["idi emiti"], "hi": ["yah kya hai"]}},
    {"slug": "how_to_get_to_airport", "translations": {"en": "How do I get to the airport?", "te": "విమానాశ్రయానికి ఎలా వెళ్ళాలి?", "hi": "हवाई अड्डे कैसे जाऊं?", "ta": "விமான நிலையத்திற்கு எப்படி செல்வது?", "kn": "ವಿಮಾನ ನಿಲ್ದಾಣಕ್ಕೆ ಹೇಗೆ ಹೋಗುವುದು?", "ml": "വിമാനത്താവളത്തിലേക്ക് എങ്ങനെ പോകാം?", "es": "¿Cómo llego al aeropuerto?", "fr": "Comment aller à l'aéroport ?"}, "translit": {"te": ["vimanashrayaniki ela vellali"], "hi": ["hawai adde kaise jaaun"]}},
    {"slug": "take_care", "translations": {"en": "Take care", "te": "జాగ్రత్త", "hi": "ख्याल रखना", "ta": "கவனமா இரு", "kn": "ಜೋಪಾನ", "ml": "സൂക്ഷിക്കണം", "es": "Cuídate", "fr": "Prends soin de toi"}, "translit": {"te": ["jagratta"], "hi": ["khyal rakhna"]}},
    {"slug": "see_you_tomorrow", "translations": {"en": "See you tomorrow", "te": "రేపు కలుద్దాం", "hi": "कल मिलते हैं", "ta": "நாளை பார்க்கலாம்", "kn": "ನಾಳೆ ಸಿಗೋಣ", "ml": "നാളെ കാണാം", "es": "Nos vemos mañana", "fr": "À demain"}, "translit": {"te": ["repu kaluddam"], "hi": ["kal milte hain"]}},
    {"slug": "i_need_a_doctor", "translations": {"en": "I need a doctor", "te": "నాకు డాక్టర్ కావాలి", "hi": "मुझे डॉक्टर चाहिए", "ta": "எனக்கு டாக்டர் தேவை", "kn": "ನನಗೆ ವೈದ್ಯರು ಬೇಕು", "ml": "എനിക്ക് ഒരു ഡോക്ടറെ വേണം", "es": "Necesito un médico", "fr": "J'ai besoin d'un médecin"}, "translit": {"te": ["naaku doctor kavali"], "hi": ["mujhe doctor chahiye"]}},
    {"slug": "call_the_police", "translations": {"en": "Call the police", "te": "పోలీసులకు కాల్ చేయండి", "hi": "पुलिस को बुलाओ", "ta": "போலீசை அழையுங்கள்", "kn": "ಪೊಲೀಸರನ್ನು ಕರೆಯಿರಿ", "ml": "പോലീസിനെ വിളിക്കൂ", "es": "Llama a la policía", "fr": "Appelez la police"}, "translit": {"te": ["policeulaku call cheyandi"], "hi": ["police ko bulao"]}},
    {"slug": "i_am_lost", "translations": {"en": "I am lost", "te": "నేను దారి తప్పిపోయాను", "hi": "मैं रास्ता भूल गया हूँ", "ta": "நான் வழி தவறிவிட்டேன்", "kn": "ನಾನು ದಾರಿ ತಪ್ಪಿದ್ದೇನೆ", "ml": "എനിക്ക് വഴി തെറ്റി", "es": "Estoy perdido", "fr": "Je suis perdu"}, "translit": {"te": ["nenu daari tappipoyanu"], "hi": ["main raasta bhool gaya hoon"]}},
]
