# Generated by Django 6.1 on 2026-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('native', models.CharField(max_length=64)),
                ('bcp47', models.CharField(max_length=16)),
                ('group', models.CharField(max_length=64)),
                ('is_phrasebook', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('translations', models.JSONField(default=dict)),
                ('translit', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
